name: dash_app_lnc
dependencies:
  - python=3.7
  - pip:
    - dash
    - plotly
    - gunicorn # for app deployment
    - nltk
    - scikit-learn
    - beautifulsoup4
    - requests
    - pandas
    - numpy
    - lxml
